### PR TITLE
Create test

### PR DESCRIPTION
**Pull request by donovamb**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/donovamb/test-cr-tools/pull/9%23issuecomment-241003407%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/donovamb/test-cr-tools/pull/9%23issuecomment-241003407%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%201%20of%201%20files%20at%20r1.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%20all%20discussions%20resolved.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/donovamb/test-cr-tools/9%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-19T12%3A18%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2476075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/donovamb%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/donovamb/test-cr-tools/pull/9#issuecomment-241003407'>General Comment</a></b>
- <a href='https://github.com/donovamb'></a> Reviewed 1 of 1 files at r1.
  Review status: all files reviewed at latest revision, all discussions resolved.
  ---
  _Comments from [Reviewable](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9)_
  

<a href='https://www.codereviewhub.com/donovamb/test-cr-tools/pull/9?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/donovamb/test-cr-tools/pull/9?approve=1'></a>&nbsp;<a href='https://github.com/donovamb/test-cr-tools/pull/9'></a>
<a href='#crh-end'></a>

---

This change is [Reviewable](https://reviewable.io/reviews/donovamb/test-cr-tools/9)

---

### CODE REVIEW

**Comment by donovamb** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9)_

**Comment by donovamb10** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9#-:-KPXjYQlXA7cwJz4fAT4:bnfp4nl)_

**Comment by donovamb10** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[a discussion](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9#-KPXje6prMfHAbat8FAM:-KPXje6q_AHlaRpBBl-3:b-xr4y53) (no related file):_
Can you test this?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9)_

**Comment by donovamb** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_[a discussion](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9#-KPXje6prMfHAbat8FAM:-KPXjn9lfdarsk3Pgwoo:bhnj9sz) (no related file):_
<details><summary>

<i>Previously, donovamb10 wrote…</i></summary>



> Can you test this?
> </details>
> Yep done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/donovamb/test-cr-tools/9)_

**Pull request closed without merging**
